export {
  delegatedAccountAbi,
  delegatedAccountFactoryAbi,
  erc20Abi,
  exchangeAbi,
  faucetAbi,
  multicall3Abi,
} from "./abi/index.js";
export {
  LIFECYCLE_EVENTS,
  blocksForDays,
  decodeIncreasePositionCollateral,
  decodePositionDecreased,
  decodePositionIncreased,
  decodePositionLiquidated,
  decodePositionOpened,
  eventTopic0,
  filterLifelineActions,
  HISTORY_TTL_MS,
  HistoryStore,
  appendRows,
  firstExchangeLogBlock,
  historyDue,
  idleAtLiquidation,
  lifelineActions,
  liquidationHistory,
  paginateLogs,
  queryHyperSync,
  recomputeHistory,
  retryAfterMs,
  summarizeLiquidations,
  totalsMatch,
  type CachedHistory,
  type HistoryPage,
  type HyperSyncEventName,
  type HyperSyncFetch,
  type HyperSyncLog,
  type IncreasePositionCollateralEvent,
  type LifelineAction,
  type LiquidationHistory,
  type LiquidationRow,
  type MarketScale,
  type PositionLiquidatedEvent,
} from "./hypersync/index.js";
export {
  AT_RISK_DISTANCE,
  BUCKET_MAX,
  BUCKET_MIN,
  COOLDOWN_BLOCKS,
  DUST_NOTIONAL_MICRO,
  LOT_SCALE,
  MICRO,
  MIN_ACTION_MICRO,
  bucketIndex,
  couldProtectNow,
  bankruptcyPricePNS,
  contractDistanceE6,
  desiredDepositMicro,
  distanceE6,
  isAtRisk,
  isDust,
  liquidationMicroFromContract,
  liquidationPriceMicro,
  liquidationPricePNS,
  type ContractMarket,
  type ContractPosition,
  lotFromNotional,
  lotToScaled,
  notionalMicro,
  maintenanceMargin,
  priceToMicro,
  replayPosition,
  sizeTopUp,
  type LifecycleStep,
  type TopUpInput,
} from "./math/index.js";
export {
  MANDATE_MAX_EXPIRY_SEC,
  MANDATE_MAX_TARGET_BPS,
  SKIP_REASONS,
  TEST_NOW_LABEL,
  armDefaults,
  armExplanation,
  armedWaitCopy,
  buildMandate,
  evalQuote,
  evaluate,
  hashMandate,
  mandateDomain,
  mandateMessage,
  mandateTypes,
  recoverSigner,
  testNowTerms,
  validateMandate,
  type ArmTerms,
  type EvalAccount,
  type EvalPosition,
  type Evaluation,
  type MandateContext,
  type MandateIssue,
  type MandateMessage,
  type MandateValidation,
  type SkipReason,
} from "./lifeline/index.js";
export {
  ORDER_CANCEL,
  ORDER_CHANGE,
  ORDER_CLOSE_LONG,
  ORDER_CLOSE_SHORT,
  ORDER_INCREASE_COLLATERAL,
  ORDER_OPEN_LONG,
  ORDER_OPEN_SHORT,
  assignOperatorTypes,
  bookPricePNS,
  factoryDomain,
  leverageHdths,
  orderDesc,
  restingAskPricePNS,
  type OrderDesc,
} from "./orders/index.js";
export {
  asAccount,
  createReadClient,
  freeBalanceCNS,
  listPerps,
  lotSums,
  openChain,
  perpIdsFromBitmap,
  POSITION_LONG,
  POSITION_PAGE_SIZE,
  POSITION_SHORT,
  readAccountByAddr,
  readAccounts,
  readExchangeSnapshot,
  readMarket,
  readPositionsForAccount,
  slicePositionPage,
  type AccountInfo,
  type AccountPosition,
  type ChainApi,
  type ChainReadOptions,
  type MarketSnapshot,
  type PerpInfo,
  type PositionNode,
} from "./chain/index.js";
export {
  ADDRESSES,
  CALIBRATED,
  CHAINS,
  CHAIN_IDS,
  GAS_LIMITS,
  HYPERSYNC_ENDPOINTS,
  MAINNET_ID,
  PUBLIC_RPC_URLS,
  TESTNET_ID,
  rpcUrls,
  type ChainAddresses,
  type ChainId,
} from "./config/index.js";

export { CRASH_LABEL, simulate, type CrashResult } from "./radar/crash.js";
export {
  PER_100K,
  forfeitCNS,
  penaltyTotals,
  reconstructResidual,
  type LiqSplit,
  type ResidualSplit,
} from "./radar/penalty.js";
export { judgeSave, markCrossed, type MarkSample, type SaveOutcome } from "./radar/saves.js";
export { radarId, radarSalt } from "./radar/anonymize.js";
export {
  assembleSnapshot,
  buildSnapshot,
  type DraftMarket,
  type DraftPosition,
  type SnapshotDraft,
} from "./radar/snapshot.js";
export {
  radarSnapshotSchema,
  type CompactPosition,
  type RadarSnapshot,
} from "./radar/schema.js";
export {
  MON_DRIP_WEI,
  acceptOwnershipTx,
  ausdTransferTx,
  createAccountTx,
  execOrderTx,
  factoryCreateTx,
  faucetRequestFundsTx,
  functionSelector,
  increasePositionCollateralTx,
  iocOpenTx,
  monDripTx,
  postOnlyMakerTx,
  revokeOperatorAllowlistTxs,
  setOperatorAllowlistTx,
  transferOwnershipTx,
  withdrawCollateralTx,
  type TxRequest,
} from "./tx/builders.js";

export const CORE_NAME = "@lifeline/core";
